const lang = {
en: {
	// Attributes
	// Offensives
	ARD: 'AR Damage',
	AMC: 'Ammo Capacity',
	CHC: 'Critical Hit Chance',
	CHD: 'Critical Hit Damage',
	DOC: 'Damage to Target Out Of Cover',
	DTA: 'Damage to Armor',
	HLD: 'Health Damage',
	HSD: 'HeadShot Damage',
	LMD: 'LGM Damage',
	MMD: 'MMR Damage',
	PTD: 'Pistol Damage',
	RFD: 'Rifle Damage',
	ROF: 'Rate of Fire',
	SGD: 'Shotgun Damage',
	SMD: 'SMG Damage',
	WHL: 'Weapon Handling',
	WPD: 'Weapon Damage',
	// Defensives
	ARG: 'Armour Regeneration',
	ARM: 'Armour',
	HLT: 'Health',
	HZP: 'Hazard Protection',
	XRS: 'Explosive Resistance',
	PFE: 'Protection from Elites',
	// Utility
	ACC: 'Accuracy',
	MAG: 'Magazine Size',
	OPR: 'Optimal Range',
	RLD: 'Reload Speed',
	SFX: 'Status Effects',
	SKD: 'Skill Damage',
	SKH: 'Skill Haste',
	SKN: 'Skill Duration',
	SKR: 'Skill Repair',
	SKT: 'Skill Tier',
	STB: 'Stability',
	SWP: 'Swap Speed',
},
fr: {},
es: {},
};
