const lang= {
en: {
	_display: `English`,
	// Attributes
	// Offensives
	CHC: `Critical Hit Chance`,
	DAR: `AR Damage`,
	DBM: `Total Weapon Damage Bonus Multiplier`,
	DCH: `Critical Hit Damage`,
	DHL: `Health Damage`,
	DHS: `HeadShot Damage`,
	DLM: `LGM Damage`,
	DMR: `MMR Damage`,
	DOC: `Damage to Target Out Of Cover`,
	DPT: `Pistol Damage`,
	DRF: `Rifle Damage`,
	DSG: `Shotgun Damage`,
	DSM: `SMG Damage`,
	DTA: `Damage to Armor`,
	DTE: `Damage to Elites`,
	DWP: `Weapon Damage`,
	DBW: `Base Weapon Damage`,
	DBA: `Total Weapon Damage Bonus Additively`,
	WRF: `Rate of Fire`,
	// Defensives
	ARG: `Armour Regeneration`,
	ARM: `Armour`,
	HIC: `Extra Incoming Healing`,
	HPP: `Health`,
	OKA: `Armour on Kill`,
	OKH: `Health on Kill`,
	PEL: `Protection from Elites`,
	PHZ: `Hazard Protection`,
	RBL: `Bleed Resistance`,
	RBR: `Burn Resistance`,
	RDF: `Bliend/Deaf Resistance`,
	RDO: `Disorient Resistance`,
	RDR: `Disrupt Resistance`,
	RNS: `Ensnare Resistance`,
	RSC: `Shock Resistance`,
	RXP: `Explosive Resistance`,
	// Utility
	DEX: `Explosive Damage`,
	SFX: `Status Effects`,
	SKD: `Skill Damage`,
	SKE: `Skill Efficiency`,
	SKH: `Skill Haste`,
	SKN: `Skill Duration`,
	SKR: `Skill Repair`,
	SKT: `Skill Tier`,
	WAC: `Accuracy`,
	WAM: `Ammo Capacity`,
	WHL: `Weapon Handling`,
	WMS: `Magazine Size`,
	WOR: `Optimal Range`,
	WRL: `Reload Speed`,
	WSB: `Stability`,
	WSW: `Swap Speed`,
	//Gears
	// Talents
	GlsCann: `Glass Cannon`,
	Vigil: `Vigilance`,
	// Guns / Weapons
	WAR: `Assault Rifle`,
	WSM: `Submachine Gun`,
	WLM: `Light Machine Gun`,
	WRF: `Rifle`,
	WMR: `Marksman Rifle`,
	WSG: `Shotgun`,
	WSA: `Sidearm`,
},
fr: {
	_display: `Français`,
},
es: {
	_display: `Español`,
},
_dfult:`en`,
};
